In [1]:
import numpy as np

In [3]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [4]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [5]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [6]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [7]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [8]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [9]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [10]:
x @ y

array([[ 28.,  64.],
       [ 67., 181.]])

In [11]:
x @ np.ones(3)

array([ 6., 15.])

In [12]:
from numpy.linalg import inv, qr

In [13]:
X = np.random.random([5, 5])

In [15]:
X

array([[0.60286898, 0.87942141, 0.76077833, 0.41724964, 0.60574231],
       [0.04158758, 0.15229948, 0.20413629, 0.82682024, 0.90429157],
       [0.23363135, 0.57653437, 0.69042101, 0.33212403, 0.12284291],
       [0.42522946, 0.45831498, 0.15610019, 0.37088615, 0.49219667],
       [0.76108201, 0.35915194, 0.17657947, 0.36888258, 0.26757347]])

In [16]:
mat = X.T.dot(X)

In [17]:
inv(mat)

array([[ 11.1000491 , -21.72336384,  16.17734967, -10.91221873,
          9.46586976],
       [-21.72336384,  51.42404157, -40.55571926,  24.85648152,
        -22.8200344 ],
       [ 16.17734967, -40.55571926,  34.20658433, -21.26709828,
         18.72936036],
       [-10.91221873,  24.85648152, -21.26709828,  25.70421839,
        -21.82225665],
       [  9.46586976, -22.8200344 ,  18.72936036, -21.82225665,
         19.90034411]])

In [19]:
X.dot(inv(X))

array([[ 1.00000000e+00,  5.55111512e-17, -2.22044605e-16,
        -8.88178420e-16,  2.22044605e-16],
       [-4.44089210e-16,  1.00000000e+00,  4.44089210e-16,
         0.00000000e+00,  5.55111512e-17],
       [-5.55111512e-17,  1.52655666e-16,  1.00000000e+00,
        -3.88578059e-16,  1.38777878e-17],
       [ 0.00000000e+00,  1.11022302e-16, -2.22044605e-16,
         1.00000000e+00, -2.77555756e-17],
       [ 0.00000000e+00, -5.55111512e-17, -1.11022302e-16,
        -1.11022302e-16,  1.00000000e+00]])

In [27]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  0.00000000e+00, -1.77635684e-15,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  3.55271368e-15,
         0.00000000e+00,  7.10542736e-15],
       [ 0.00000000e+00, -3.55271368e-15,  1.00000000e+00,
        -3.55271368e-15,  0.00000000e+00],
       [-1.77635684e-15, -3.55271368e-15, -3.55271368e-15,
         1.00000000e+00,  0.00000000e+00],
       [-1.77635684e-15,  0.00000000e+00,  0.00000000e+00,
         7.10542736e-15,  1.00000000e+00]])

In [28]:
q, r = qr(mat)

In [29]:
r

array([[-2.17581405, -2.63284482, -2.17536187, -2.24215545, -2.41500808],
       [ 0.        , -0.38180889, -0.48385555, -0.3255062 , -0.3447968 ],
       [ 0.        ,  0.        , -0.06054613,  0.25537653,  0.37191825],
       [ 0.        ,  0.        ,  0.        , -0.64220219, -0.722996  ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.02335467]])

In [30]:
q

array([[-0.54224766,  0.75486629, -0.24567079,  0.16406485,  0.22107226],
       [-0.52368412, -0.23371046,  0.31606666,  0.53590658, -0.53295437],
       [-0.38110474, -0.60176264, -0.5364032 ,  0.11652459,  0.43741803],
       [-0.3685924 , -0.04286034, -0.26420085, -0.72990122, -0.5096516 ],
       [-0.38809952, -0.10770803,  0.69441864, -0.37356805,  0.46476597]])

<img src = '../Python/factori_qr.png'>