In [1]:
import numpy as np

In [2]:
arr = np.random.randn(6)

In [3]:
arr

array([-0.0944648 ,  0.60200819, -0.81130978,  1.22110756,  0.29434164,
        0.73584278])

In [4]:
arr.sort()

In [5]:
arr

array([-0.81130978, -0.0944648 ,  0.29434164,  0.60200819,  0.73584278,
        1.22110756])

In [6]:
arr = np.random.randn(5, 3)
arr

array([[-0.70132927,  1.47686954, -0.73649658],
       [-1.48717066, -1.43289107,  0.39712996],
       [ 0.25128094, -1.70091034, -1.39843878],
       [-0.27508717, -0.32256306, -0.94824282],
       [ 2.53044149,  0.04461153,  0.1689514 ]])

In [7]:
arr.sort(1)
arr

array([[-0.73649658, -0.70132927,  1.47686954],
       [-1.48717066, -1.43289107,  0.39712996],
       [-1.70091034, -1.39843878,  0.25128094],
       [-0.94824282, -0.32256306, -0.27508717],
       [ 0.04461153,  0.1689514 ,  2.53044149]])

In [8]:
arr.sort(0)
arr

array([[-1.70091034, -1.43289107, -0.27508717],
       [-1.48717066, -1.39843878,  0.25128094],
       [-0.94824282, -0.70132927,  0.39712996],
       [-0.73649658, -0.32256306,  1.47686954],
       [ 0.04461153,  0.1689514 ,  2.53044149]])

In [10]:
large_arr = np.random.randn(1000)
large_arr.sort()

In [13]:
quantile = [0.05, 0.1, 0.5, 0.75, 0.8, 0.9, 0.99]

In [14]:
for i in quantile:
    print(large_arr[int(i * len(large_arr))])

-1.5777300785842105
-1.2831946619085002
0.0030926174509195914
0.688099819543523
0.8225394474904949
1.231937182094891
2.2981173222136753
