In [1]:
import numpy as np

In [3]:
arr = np.arange(6)

In [7]:
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)

In [9]:
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 1.6645132 ,  0.79555568],
       [ 0.43350935,  0.59827771],
       [ 1.07909669, -0.10519889]])

In [10]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 1.6645132 ,  0.79555568,  3.        ],
       [ 0.43350935,  0.59827771,  4.        ],
       [ 1.07909669, -0.10519889,  5.        ]])

In [12]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])