In [1]:
import numpy as np

In [2]:
arr = np.random.randn(4, 4)
arr

array([[-0.55100272,  0.27651099, -1.03838768, -0.10700526],
       [-0.26379864, -0.30463871,  0.86124507, -0.81746766],
       [-0.53463175,  0.02793354, -0.00494703, -0.63301567],
       [-0.58577025,  0.60627031,  0.13943604,  0.77572995]])

In [3]:
arr.std(axis = 0)

array([0.12835361, 0.33383191, 0.67804943, 0.61834106])

In [4]:
arr.sum(0), arr.sum(axis = 0)

(array([-1.93520336,  0.60607612, -0.0426536 , -0.78175864]),
 array([-1.93520336,  0.60607612, -0.0426536 , -0.78175864]))

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum() # [0, 0 + 1, 0 + 1 + 2, 0 + 1 + 2 + 3, 0 + 1 + 2 + 3 + 4...]

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [6]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [8]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
arr.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [10]:
arr.cumsum(axis = 1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])