In [1]:
import numpy as np

In [5]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
arr.reshape([4, 2])


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [8]:
arr.reshape([4, 2], order='A')
# Lea los elementos de a usando este orden de índice y coloque los elementos en la matriz remodelada usando este orden de índice. 
# 'C' significa leer / escribir los elementos usando un orden de índice similar a C, con el índice del último eje cambiando más rápido, 
# de regreso al índice del primer eje cambiando más lento. 'F' significa leer / escribir los elementos usando un orden de índice similar a Fortran,
# con el primer índice cambiando más rápido y el último índice cambiando más lento. Tenga en cuenta que las opciones 'C' y 'F' 
# no tienen en cuenta el diseño de la memoria de la matriz subyacente y solo se refieren al orden de indexación. 'A' 
# significa leer / escribir los elementos en un orden de índice similar a Fortran si a es contiguo a Fortran en la memoria, de lo contrario, en un orden similar a C.

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [9]:
arr.reshape([4, 2], order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [10]:
arr.reshape([4, 2], order='F')

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])